### ISSUE TITLE
Access to viewModel from create state in previewFragment

### ISSUE THREAD

**Issue by sirambd** [Infomaniak/android-kDrive#166]
From previewFragment the viewmodel is sometimes not instantiated, and we have the following error:
```
java.lang.IllegalStateException: You cannot access the NavBackStackEntry's ViewModels until it is added to the NavController's back stack (i.e., the Lifecycle of the NavBackStackEntry reaches the CREATED state).
    at androidx.navigation.NavBackStackEntry.getViewModelStore(NavBackStackEntry.kt:174)
    at com.infomaniak.drive.ui.fileList.preview.PreviewFragment$special$$inlined$navGraphViewModels$default$2.invoke(NavGraphViewModelLazy.kt:59)
    at com.infomaniak.drive.ui.fileList.preview.PreviewFragment$special$$inlined$navGraphViewModels$default$2.invoke(NavGraphViewModelLazy.kt:58)
    at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:53)
    at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
    at com.infomaniak.drive.ui.fileList.preview.PreviewFragment.getPreviewSliderViewModel(PreviewFragment.kt:34)
    at com.infomaniak.drive.ui.fileList.preview.PreviewFragment.onCreate(PreviewFragment.kt:40)
    at androidx.fragment.app.Fragment.performCreate(Fragment.java:2947)
    at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:455)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:255)
    at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1327)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2757)
    at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2689)
    at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1902)
    at androidx.fragment.app.Fragment.onCreate(Fragment.java:1878)
    at androidx.fragment.app.Fragment.performCreate(Fragment.java:2947)
    at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:455)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:255)
    at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1327)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2757)
    at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2689)
    at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1902)
    at androidx.fragment.app.Fragment.onCreate(Fragment.java:1878)
    at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:164)
    at androidx.fragment.app.Fragment.performCreate(Fragment.java:2947)
    at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:455)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:255)
    at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1327)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2757)
    at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2689)
    at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:251)
    at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:252)
    at com.infomaniak.drive.ui.BaseActivity.onCreate(BaseActivity.kt:28)
    at com.infomaniak.drive.ui.MainActivity.onCreate(MainActivity.kt:95)
    at android.app.Activity.performCreate(Activity.java:8086)
    at android.app.Activity.performCreate(Activity.java:8074)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8178)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.infomaniak.drive/com.infomaniak.drive.ui.MainActivity}: java.lang.IllegalStateException: You cannot access the NavBackStackEntry's ViewModels until it is added to the NavController's back stack (i.e., the Lifecycle of the NavBackStackEntry reaches the CREATED state).
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8178)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Steps to reproduce**
No more informations

**Comment by sirambd** [comment]
New Fragment [Update - alpha 06 ](https://developer.android.com/jetpack/androidx/releases/navigation#2.4.0-alpha06) fixes status issues with the NavBackStackEntry.
to check if its corrects the problem here
commit https://github.com/Infomaniak/android-kDrive/pull/167/commits/1a3e5866d02c3272854b5a73fda7545d5e230f8e
