### ISSUE TITLE
Mauvaise prise en charge de fichiers vidéos

### ISSUE THREAD

**Issue by ik-tjacobse** [Infomaniak/android-kDrive#169]
Impossible de lire en entier mes fichiers audios .wav et .flac. Lecture normale au début puis coupure brusque avec l'erreur : "Fichier vidéo non pris en charge par le lecteur vidéo". 

Appareil : Huawei HUAWEI P30
Langue de l'appareil : Français
Code de la version de l'application : 40002201
Nom de la version de l'application : 4.0.22
Version d'Android : Android 10 (SDK 29)

Source: Google Play

**Comment by Kilian-Perisset** [comment]
Effectivement, la version < 4.0 permettait de lire ses vidéos/audio à travers un service, c'est donc une régression (ajouté au board).

Concernant le bug, on a pas été en mesure de le reproduire efficacement jusqu'à présent (même avec des FLAC), tu as plus d'informations ?

**Comment by ik-tjacobse** [comment]
@Kilian-Perisset lorsqu'il s'agit de retours du Google Play, il n'y a pas plus de détails. Le client a été invité à prendre contact avec le support, mais c'est sans garantie. Cela vaut la peine de tenter de reproduire le problème par nos propres moyens lorsqu'ils sont récurrents, ou de consulter le support.

**Comment by nicolasleperlier** [comment]
Bonjour ! Je suis à l'origine du commentaire. Voici un des fichiers WAV qui coupent :
https://drive.infomaniak.com/app/share/176886/463bd9f8-64c2-40a5-a3d8-e1a4971438b2
La lecture ne rencontre aucun problème sur navigateur mobile, uniquement quand la lecture se fait sur l'appli. Le fichier a été acheté et provient directement du site https://www.junodownload.com/
--
Et voici un des fichiers FLAC 
https://drive.infomaniak.com/app/share/176886/51c52c97-bf13-4ba1-ac02-d4e744a3e6cb
Un RIP personnel d'un album CD

Pour reproduire le bug il faut laisser les fichiers lire parfois 1 minute.

**Comment by Kilian-Perisset** [comment]
Bonjour Nicolas, 

Merci beaucoup pour votre réactivité et votre contribution. 
J'avais personnellement essayé plusieurs fichiers audio non-compressés, de taille variée sans jamais réussir à reproduire. 

On va prochainement regarder ce souci plus en détails et essayer avec les échantillons fournis, vous pouvez consulter les tâches en cours sur le board : https://github.com/Infomaniak/android-kDrive/projects/1

Bonne journée !

**Comment by Kilian-Perisset** [comment]
```
2021-08-10 08:03:45.071 29405-30528/com.infomaniak.drive E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: timeout
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.read(OkHttpDataSource.java:373)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:206)
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:283)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:63)
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:176)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:579)
        at com.google.android.exoplayer2.extractor.TrackOutput.sampleData(TrackOutput.java:159)
        at com.google.android.exoplayer2.extractor.wav.WavExtractor$PassthroughOutputWriter.sampleData(WavExtractor.java:258)
        at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:139)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1049)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:379)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
        at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.readInternal(OkHttpDataSource.java:491)
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.read(OkHttpDataSource.java:370)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:206) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:283) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:63) 
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:176) 
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:579) 
        at com.google.android.exoplayer2.extractor.TrackOutput.sampleData(TrackOutput.java:159) 
        at com.google.android.exoplayer2.extractor.wav.WavExtractor$PassthroughOutputWriter.sampleData(WavExtractor.java:258) 
        at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:139) 
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1049) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2021-08-10 08:03:45.080 29405-29405/com.infomaniak.drive D/EventLogger: audioDisabled [eventTime=104.42, mediaPos=96.70, window=0, period=0]
2021-08-10 08:03:45.083 29405-29405/com.infomaniak.drive E/EventLogger: playerFailed [eventTime=104.42, mediaPos=96.70, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: timeout
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.read(OkHttpDataSource.java:373)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:206)
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:283)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:63)
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:176)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:579)
        at com.google.android.exoplayer2.extractor.TrackOutput.sampleData(TrackOutput.java:159)
        at com.google.android.exoplayer2.extractor.wav.WavExtractor$PassthroughOutputWriter.sampleData(WavExtractor.java:258)
        at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:139)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1049)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:379)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
        at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.readInternal(OkHttpDataSource.java:491)
        at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.read(OkHttpDataSource.java:370)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:206) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:283) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:63) 
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:176) 
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:579) 
        at com.google.android.exoplayer2.extractor.TrackOutput.sampleData(TrackOutput.java:159) 
        at com.google.android.exoplayer2.extractor.wav.WavExtractor$PassthroughOutputWriter.sampleData(WavExtractor.java:258) 
        at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:139) 
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1049) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
    ]
```

**Comment by nicolasleperlier** [comment]
Bonjour, 
Pourrais-je avoir une mise à jour à propos du bug ? Est-il résolu ?

**Comment by Kilian-Perisset** [comment]
Bonjour, 
Il n'est pas encore résolu... il s'agit d'un changement radical du fonctionnement actuel du player.
On devrait se pencher sur ce problème durant la semaine 👍

**Comment by Kilian-Perisset** [comment]
@nicolasleperlier en y repensant, je n'ai pas donné de solution alternative. 

Si jamais, vous avez la possibilité de lire vos fichiers audio et vidéo sur un lecteur externe (type VLC) en cliquant sur le bouton présent en haut à droite lors de la lecture du média (ou le bouton `Ouvrir avec` dans le menu). C'est en effet contraignant, mais à défaut vous pourrez lire vos fichiers audio/vidéo pendant la résolution du problème.
