### ISSUE TITLE
Video streaming keep crashing

### ISSUE THREAD

**Issue by woodruffandtheschnibbleofazimuth** [Infomaniak/android-kDrive#189]
Hello,
I have kDrive version 4.0.23 (40002301) with Android 11.

When I try to stream a video longer than 30sec it keeps crashing. It streams nice until 30sec then starts to freezing andò crashing after a few seconds with no error. The app just close.

**Comment by Kilian-Perisset** [comment]
Hi, 
Thanks for your issue 👍 

Your bug seems to be related to this issue : https://github.com/Infomaniak/android-kDrive/issues/169 
The app doesn't crash/close but the player displays a message like "Unable to read this file".

If that's not the same bug, may I ask you to provide us the file that makes the app crash ?

**Comment by woodruffandtheschnibbleofazimuth** [comment]
Yes it seems similar but i don't receive any error.

If it can help: i notice that it happens only when the file is in a folder with other images/videos.
The same video on empty folder works fine. If I copy the video on a folder with other videos it crash after 30/40 seconds.

Videos is just .mp4 made by smartphone.

I made a video-screenshot of what happens, if you want i can post it somewhere.

**Comment by Kilian-Perisset** [comment]
@woodruffandtheschnibbleofazimuth 

> If it can help: i notice that it happens only when the file is in a folder with other images/videos.
It seems strange that app crashes because of multiple video files 🤔, I'll try to reproduce a similar use-case

> I made a video-screenshot of what happens, if you want i can post it somewhere.

Great ! It would be greatly appreciated, try to post it in this issue, and if not possible you can upload it here : https://www.swisstransfer.com/ and give us the link

**Comment by JorisBodin** [comment]
We will update exoplayer, a new version is available since a few days: https://github.com/google/ExoPlayer/releases/tag/r2.15.0

**Comment by woodruffandtheschnibbleofazimuth** [comment]
> @woodruffandtheschnibbleofazimuth
> 
> > If it can help: i notice that it happens only when the file is in a folder with other images/videos.
> 
> It seems strange that app crashes because of multiple video files 🤔, I'll try to reproduce a similar use-case
> 
> > I made a video-screenshot of what happens, if you want i can post it somewhere.
> 
> Great ! It would be greatly appreciated, try to post it in this issue, and if not possible you can upload it here : https://www.swisstransfer.com/ and give us the link

Yes, here you find the screenvideo of what happens. As you can see at ~30sec it slows down, freeze and the app crash/close.
This happens with every big video (+100mb). I have tried with long videos but much less heavy and it works fine.

Link to screenvideo:
https://www.swisstransfer.com/d/d15c7812-20c0-4bf0-b505-f447ec688e25

**Comment by Kilian-Perisset** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: OkHttp TaskRunner
    Process: com.infomaniak.drive, PID: 22839
    java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 660240 free bytes and 644KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 786432 bytes)
        at okio.Segment.<init>(Segment.kt:62)
        at okio.SegmentPool.take(SegmentPool.kt:88)
        at okio.Buffer.writableSegment$okio(Buffer.kt:1414)
        at okio.InputStreamSource.read(JvmOkio.kt:91)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
        at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
        at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
        at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
        at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
E/EventLogger: internalError [eventTime=8.68, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
      ```

**Comment by Kilian-Perisset** [comment]
Out of memory - 
This bug happens when file is locally present on the device too. Possible solutions : 
- Determine if this is our exoplayer configuration which is not adequate
- Change the player
- Stream file directly from server without pre-treatment by device
