### ISSUE TITLE
Realm too many open files in gallery

### ISSUE THREAD

**Issue by LunarX** [Infomaniak/android-kDrive#742]
When very quickly scrolling through images realm conplains about too many open files and crashes.

Only got reproduced on the one plus phone we have.

Stack trace:
```
2022-04-07 15:49:27.790 E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-15
    Process: com.infomaniak.drive, PID: 5415
    io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/com.infomaniak.drive/files/kDrive-1043888-140946.realm.management/access_control.control.mx': open() failed: Too many open files Path: /data/user/0/com.infomaniak.drive/files/kDrive-1043888-140946.realm.management/access_control.control.mx
    Exception backtrace:
    <backtrace not supported on this platform>. (open("/data/user/0/com.infomaniak.drive/files/kDrive-1043888-140946.realm.management/access_control.control.mx") failed: Too many open files Path: /data/user/0/com.infomaniak.drive/files/kDrive-1043888-140946.realm.management/access_control.control.mx
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/user/0/com.infomaniak.drive/files/kDrive-1043888-140946.realm.management/access_control.control.mx) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: ACCESS_ERROR.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:176)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:261)
        at io.realm.BaseRealm.<init>(BaseRealm.java:143)
        at io.realm.BaseRealm.<init>(BaseRealm.java:110)
        at io.realm.Realm.<init>(Realm.java:159)
        at io.realm.Realm.createInstance(Realm.java:506)
        at io.realm.RealmCache.createInstance(RealmCache.java:508)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:461)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:422)
        at io.realm.Realm.getInstance(Realm.java:435)
        at com.infomaniak.drive.data.cache.FileController.getRealmInstance(FileController.kt:314)
        at com.infomaniak.drive.data.cache.FileController.getRealmInstance$default(FileController.kt:314)
        at com.infomaniak.drive.data.cache.FileController.storePicturesDrive(FileController.kt:524)
        at com.infomaniak.drive.data.cache.FileController.storePicturesDrive$default(FileController.kt:515)
        at com.infomaniak.drive.ui.menu.PicturesViewModel.emitApiPictures(PicturesViewModel.kt:71)
        at com.infomaniak.drive.ui.menu.PicturesViewModel.fetchApiPictures(PicturesViewModel.kt:57)
        at com.infomaniak.drive.ui.menu.PicturesViewModel.access$fetchApiPictures(PicturesViewModel.kt:32)
        at com.infomaniak.drive.ui.menu.PicturesViewModel$getLastPictures$1.invokeSuspend(PicturesViewModel.kt:46)
        at com.infomaniak.drive.ui.menu.PicturesViewModel$getLastPictures$1.invoke(Unknown Source:8)
        at com.infomaniak.drive.ui.menu.PicturesViewModel$getLastPictures$1.invoke(Unknown Source:4)
        at androidx.lifecycle.BlockRunner$maybeRun$1.invokeSuspend(CoroutineLiveData.kt:176)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-04-07 15:49:27.797 W/OPDiagnose: getService:OPDiagnoseService NULL
2022-04-07 15:49:27.805 A/Looper: Could not create epoll instance: Too many open files
2022-04-07 15:49:28.128 W/nfomaniak.driv: ashmem_create_region failed for 'indirect ref table': Too many open files
2022-04-07 15:49:27.792 E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-15
    Process: com.infomaniak.drive, PID: 5415
    io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/com.infomaniak.drive/files/kDrive-1043888-140946.realm.management/access_control.control.mx': open() failed: Too many open files Path: /data/user/0/com.infomaniak.drive/files/kDrive-1043888-140946.realm.management/access_control.control.mx
    Exception backtrace:
    <backtrace not supported on this platform>. (open("/data/user/0/com.infomaniak.drive/files/kDrive-1043888-140946.realm.management/access_control.control.mx") failed: Too many open files Path: /data/user/0/com.infomaniak.drive/files/kDrive-1043888-140946.realm.management/access_control.control.mx
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/user/0/com.infomaniak.drive/files/kDrive-1043888-140946.realm.management/access_control.control.mx) in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: ACCESS_ERROR.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:176)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:261)
        at io.realm.BaseRealm.<init>(BaseRealm.java:143)
        at io.realm.BaseRealm.<init>(BaseRealm.java:110)
        at io.realm.Realm.<init>(Realm.java:159)
        at io.realm.Realm.createInstance(Realm.java:506)
        at io.realm.RealmCache.createInstance(RealmCache.java:508)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:461)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:422)
        at io.realm.Realm.getInstance(Realm.java:435)
        at com.infomaniak.drive.data.cache.FileController.getRealmInstance(FileController.kt:314)
        at com.infomaniak.drive.data.cache.FileController.getRealmInstance$default(FileController.kt:314)
        at com.infomaniak.drive.data.cache.FileController.storePicturesDrive(FileController.kt:524)
        at com.infomaniak.drive.data.cache.FileController.storePicturesDrive$default(FileController.kt:515)
        at com.infomaniak.drive.ui.menu.PicturesViewModel.emitApiPictures(PicturesViewModel.kt:71)
        at com.infomaniak.drive.ui.menu.PicturesViewModel.fetchApiPictures(PicturesViewModel.kt:57)
        at com.infomaniak.drive.ui.menu.PicturesViewModel.access$fetchApiPictures(PicturesViewModel.kt:32)
        at com.infomaniak.drive.ui.menu.PicturesViewModel$getLastPictures$1.invokeSuspend(PicturesViewModel.kt:46)
        at com.infomaniak.drive.ui.menu.PicturesViewModel$getLastPictures$1.invoke(Unknown Source:8)
        at com.infomaniak.drive.ui.menu.PicturesViewModel$getLastPictures$1.invoke(Unknown Source:4)
        at androidx.lifecycle.BlockRunner$maybeRun$1.invokeSuspend(CoroutineLiveData.kt:176)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Lnamw** [comment]
Issue cleanup 🧹
